CREATE TABLE IF NOT EXISTS users(
user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar NOT NULL,
login varchar NOT NULL,
name varchar,
birthday date);

CREATE TABLE IF NOT EXISTS ratings(
rating_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar UNIQUE NOT NULL);

CREATE TABLE IF NOT EXISTS films(
film_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar NOT NULL,
description varchar(200),
release_date date,
duration bigint,
rating_id bigint,
FOREIGN KEY (rating_id) REFERENCES ratings (rating_id));

CREATE TABLE IF NOT EXISTS friendships(
user_id bigint NOT NULL,
user_id_friend bigint NOT NULL,
FOREIGN KEY (user_id) REFERENCES users (user_id),
FOREIGN KEY (user_id_friend) REFERENCES users (user_id),
CONSTRAINT not_equal_to_himself CHECK (user_id <> user_id_friend));

CREATE TABLE IF NOT EXISTS film_likes(
user_id bigint NOT NULL,
film_id bigint NOT NULL,
FOREIGN KEY (user_id) REFERENCES users (user_id),
FOREIGN KEY (film_id) REFERENCES films (film_id));

CREATE TABLE IF NOT EXISTS genres(
genre_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar UNIQUE NOT NULL);

CREATE TABLE IF NOT EXISTS film_genres(
film_id bigint NOT NULL,
genre_id bigint NOT NULL,
FOREIGN KEY (genre_id) REFERENCES genres (genre_id),
FOREIGN KEY (film_id) REFERENCES films (film_id));